# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addLession.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.addlession_control import Lession_control
from datetime import datetime



class AddLessionWindow(object):
    def setupUi(self, MainWindow,id):
        self.lession_controller = Lession_control()
        self.course_id = id
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:#F5F7FA;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(270, 0, 641, 111))
        self.label.setStyleSheet("\n"
"color: 2C3E50 ;\n"
"border: none;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(200, 120, 721, 321))
        self.widget.setStyleSheet("border:none;")
        self.widget.setObjectName("widget")
        self.idstudenttxt = QtWidgets.QLineEdit(self.widget)
        self.idstudenttxt.setGeometry(QtCore.QRect(260, 30, 451, 101))
        self.idstudenttxt.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.idstudenttxt.setObjectName("idstudenttxt")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 241, 50))
        self.label_2.setStyleSheet("color: rgb(44, 62, 80);                          \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.label_2.setObjectName("label_2")
        self.btnRegister = QtWidgets.QPushButton(self.widget)
        self.btnRegister.setGeometry(QtCore.QRect(10, 180, 711, 61))
        self.btnRegister.setStyleSheet("background-color:#2C3E50;\n"
"    color: white;\n"
"    border: 1.5px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnRegister.setObjectName("btnRegister")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#2c3e50;\">ADD LESSON</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Name lesson"))
        self.btnRegister.setText(_translate("MainWindow", "Add"))
        self.btnRegister.clicked.connect(self.handle_add_lession)

    
    def handle_add_lession(self):
        name = self.idstudenttxt.text().strip()
        if name:
            current_date = datetime.now().strftime("%Y-%m-%d")  
            result = self.lession_controller.insert_lession(self.course_id,current_date,name)
            if result:
               QtWidgets.QMessageBox.information(None, "Success", "Lesson successed!")
               self.close()
            else:
               QtWidgets.QMessageBox.warning(None, "Error", "Lesson exits.")
               
        else:
            QtWidgets.QMessageBox.warning(None, "Error", "Enter again.")


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = AddLessionWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
