# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendent_techer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.attendance_teacher_control import AttendanceController


class Attendance_MainWindow(object):
    def setupUi(self, MainWindow, id):
        self.course_id = id
        self.attendance_controller = AttendanceController()
        

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 976)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:#F5F7FA;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(270, 0, 551, 111))
        self.label.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(250, 110, 841, 121))
        self.widget.setStyleSheet("border:none;\n"
"margin: 10px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStartCheckin = QtWidgets.QPushButton(self.widget)
        self.btnStartCheckin.setStyleSheet("background-color:#2C3E50;\n"
"    color: white;\n"
"    border: 1.5px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnStartCheckin.setObjectName("btnStartCheckin")
        self.horizontalLayout.addWidget(self.btnStartCheckin)
        self.btnEndCheckin = QtWidgets.QPushButton(self.widget)
        self.btnEndCheckin.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnEndCheckin.setObjectName("btnEndCheckin")
        self.horizontalLayout.addWidget(self.btnEndCheckin)
        self.Skipcheckin = QtWidgets.QCheckBox(self.widget)
        self.Skipcheckin.setStyleSheet("QCheckBox {\n"
"    color: #2C3E50;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    border: 2px solid #2C3E50;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #2C3E50;\n"
"}\n"
"")
        self.Skipcheckin.setObjectName("Skipcheckin")
        self.horizontalLayout.addWidget(self.Skipcheckin)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(240, 230, 851, 121))
        self.widget_2.setStyleSheet("border:none;\n"
"margin: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnStartCheckout = QtWidgets.QPushButton(self.widget_2)
        self.btnStartCheckout.setStyleSheet("background-color:#2C3E50;\n"
"    color: white;\n"
"    border: 1.5px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnStartCheckout.setObjectName("btnStartCheckout")
        self.horizontalLayout_2.addWidget(self.btnStartCheckout)
        self.btnEndCheckout = QtWidgets.QPushButton(self.widget_2)
        self.btnEndCheckout.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnEndCheckout.setObjectName("btnEndCheckout")
        self.horizontalLayout_2.addWidget(self.btnEndCheckout)
        self.Skipcheckout = QtWidgets.QCheckBox(self.widget_2)
        self.Skipcheckout.setStyleSheet("QCheckBox {\n"
"    color: #2C3E50;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    border: 2px solid #2C3E50;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #2C3E50;\n"
"}\n"
"")
        self.Skipcheckout.setObjectName("Skipcheckout")
        self.horizontalLayout_2.addWidget(self.Skipcheckout)
        self.Skipall = QtWidgets.QCheckBox(self.frame)
        self.Skipall.setGeometry(QtCore.QRect(440, 350, 430, 44))
        self.Skipall.setStyleSheet("QCheckBox {\n"
"    color: #2C3E50;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    border: 2px solid #2C3E50;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #2C3E50;\n"
"}\n"
"")
        self.Skipall.setObjectName("Skipall")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 231, 51))
        self.label_2.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 260, 231, 51))
        self.label_3.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 350, 361, 48))
        self.label_4.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 410, 321, 51))
        self.label_5.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 480, 581, 51))
        self.label_6.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.label_6.setObjectName("label_6")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(10, 530, 1081, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1079, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableStudentAttendence = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableStudentAttendence.setObjectName("tableStudentAttendence")
        self.tableStudentAttendence.setColumnCount(5)
        self.tableStudentAttendence.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStudentAttendence.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStudentAttendence.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStudentAttendence.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStudentAttendence.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStudentAttendence.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.tableStudentAttendence)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.status = QtWidgets.QLabel(self.frame)
        self.status.setGeometry(QtCore.QRect(470, 410, 321, 51))
        self.status.setStyleSheet("color: 2C3E50 ;\n"
"border: none;")
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#2c3e50;\">ATTENDANCE</span></p></body></html>"))
        self.btnStartCheckin.setText(_translate("MainWindow", "Start"))
        self.btnEndCheckin.setText(_translate("MainWindow", "End"))
        self.Skipcheckin.setText(_translate("MainWindow", "Skip"))
        self.btnStartCheckout.setText(_translate("MainWindow", "Start"))
        self.btnEndCheckout.setText(_translate("MainWindow", "End"))
        self.Skipcheckout.setText(_translate("MainWindow", "Skip"))
        self.Skipall.setText(_translate("MainWindow", "Skip"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#2c3e50;\">Check in:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#2c3e50;\">Check out:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#2c3e50;\">Skip Attendance:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#2c3e50;\">Status:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#2c3e50;\">List Student Attendance:</span></p></body></html>"))
        item = self.tableStudentAttendence.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableStudentAttendence.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableStudentAttendence.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableStudentAttendence.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableStudentAttendence.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        self.status.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ff0000;\">None....</span></p></body></html>"))
        self.btnStartCheckin.clicked.connect(self.handle_check_in)

    def handle_check_in(self):
        print("đã vào")
        success = self.attendance_controller.check_in(self.course_id)

        if success:
            QtWidgets.QMessageBox.information(None, "Thông báo", "Check in status.")
            self.status.setText("Checkin Loading....")
        else:
            QtWidgets.QMessageBox.warning(None, "Lỗi", "Điểm danh vào thất bại.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Attendance_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
