from models.Student import Student
from models.Teacher import Teacher

from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.schedule_controller import ScheduleController

class Ui_Home(object):
    def setupUi(self, MainWindow,user):
        self.user = user
        self.schedule_controller = ScheduleController()
        
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1416, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setMinimumSize(QtCore.QSize(120, 0))
        self.widget.setSizeIncrement(QtCore.QSize(100, 0))
        self.widget.setStyleSheet("background-color:#F5F7FA;\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_12.setStyleSheet("border: none")
        self.pushButton_12.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/logo_vku.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.pushButton_12)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timetablebtn = QtWidgets.QPushButton(self.widget)
        self.timetablebtn.setMinimumSize(QtCore.QSize(100, 100))
        self.timetablebtn.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.timetablebtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("icon/Documents/Python/qt5/icon/table1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.timetablebtn.setIcon(icon1)
        self.timetablebtn.setIconSize(QtCore.QSize(100, 100))
        self.timetablebtn.setCheckable(True)
        self.timetablebtn.setAutoExclusive(True)
        self.timetablebtn.setObjectName("timetablebtn")
        self.verticalLayout.addWidget(self.timetablebtn)
        self.historybtn = QtWidgets.QPushButton(self.widget)
        self.historybtn.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.historybtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historybtn.setIcon(icon2)
        self.historybtn.setIconSize(QtCore.QSize(100, 100))
        self.historybtn.setCheckable(True)
        self.historybtn.setAutoExclusive(True)
        self.historybtn.setObjectName("historybtn")
        self.verticalLayout.addWidget(self.historybtn)
        self.userbtn = QtWidgets.QPushButton(self.widget)
        self.userbtn.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.userbtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userbtn.setIcon(icon3)
        self.userbtn.setIconSize(QtCore.QSize(100, 100))
        self.userbtn.setCheckable(True)
        self.userbtn.setAutoExclusive(True)
        self.userbtn.setObjectName("userbtn")
        self.verticalLayout.addWidget(self.userbtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 238, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.logoutbtn = QtWidgets.QPushButton(self.widget)
        self.logoutbtn.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.logoutbtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutbtn.setIcon(icon4)
        self.logoutbtn.setIconSize(QtCore.QSize(100, 100))
        self.logoutbtn.setCheckable(True)
        self.logoutbtn.setAutoExclusive(True)
        self.logoutbtn.setObjectName("logoutbtn")
        self.verticalLayout_2.addWidget(self.logoutbtn)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color:#F5F7FA;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.hide() 
       
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setStyleSheet("border: none")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.lb_4 = QtWidgets.QLabel(self.widget_2)
        self.lb_4.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 24px; \n"
"font-weight: bold; ")
        self.lb_4.setObjectName("lb_4")
        self.verticalLayout_4.addWidget(self.lb_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timetabebtn2 = QtWidgets.QPushButton(self.widget_2)
        self.timetabebtn2.setStyleSheet("border: 1.5px solid #2C3E50;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timetabebtn2.setIcon(icon5)
        self.timetabebtn2.setIconSize(QtCore.QSize(100, 100))
        self.timetabebtn2.setCheckable(True)
        self.timetabebtn2.setAutoExclusive(True)
        self.timetabebtn2.setObjectName("timetabebtn2")
        self.verticalLayout_3.addWidget(self.timetabebtn2)
        self.historybtn_2 = QtWidgets.QPushButton(self.widget_2)
        self.historybtn_2.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.historybtn_2.setIcon(icon2)
        self.historybtn_2.setIconSize(QtCore.QSize(100, 100))
        self.historybtn_2.setCheckable(True)
        self.historybtn_2.setAutoExclusive(True)
        self.historybtn_2.setObjectName("historybtn_2")
        self.verticalLayout_3.addWidget(self.historybtn_2)
        self.userbtn_2 = QtWidgets.QPushButton(self.widget_2)
        self.userbtn_2.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.userbtn_2.setIcon(icon3)
        self.userbtn_2.setIconSize(QtCore.QSize(100, 100))
        self.userbtn_2.setCheckable(True)
        self.userbtn_2.setAutoExclusive(True)
        self.userbtn_2.setObjectName("userbtn_2")
        self.verticalLayout_3.addWidget(self.userbtn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.logoutbtn_2 = QtWidgets.QPushButton(self.widget_2)
        self.logoutbtn_2.setStyleSheet("border: 1.5px solid #2C3E50;")
        self.logoutbtn_2.setIcon(icon4)
        self.logoutbtn_2.setIconSize(QtCore.QSize(100, 100))
        self.logoutbtn_2.setCheckable(True)
        self.logoutbtn_2.setAutoExclusive(True)
        self.logoutbtn_2.setObjectName("logoutbtn_2")
        self.verticalLayout_4.addWidget(self.logoutbtn_2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("background-color:#F5F7FA;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menubtn = QtWidgets.QPushButton(self.widget_4)
        self.menubtn.setStyleSheet("border:none;")
        self.menubtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menubtn.setIcon(icon6)
        self.menubtn.setIconSize(QtCore.QSize(40, 40))
        self.menubtn.setCheckable(True)
        self.menubtn.setObjectName("menubtn")
        self.horizontalLayout_3.addWidget(self.menubtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditFind = QtWidgets.QLineEdit(self.widget_4)
        self.lineEditFind.setMinimumSize(QtCore.QSize(100, 50))
        self.lineEditFind.setStyleSheet("background-color: white;")
        self.lineEditFind.setObjectName("lineEditFind")
        self.horizontalLayout_2.addWidget(self.lineEditFind)
        self.findbtn = QtWidgets.QPushButton(self.widget_4)
        self.findbtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findbtn.setIcon(icon7)
        self.findbtn.setIconSize(QtCore.QSize(40, 40))
        self.findbtn.setObjectName("findbtn")
        self.horizontalLayout_2.addWidget(self.findbtn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(304, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lb_5 = QtWidgets.QLabel(self.page)
        self.lb_5.setGeometry(QtCore.QRect(10, 40, 251, 45))
        self.lb_5.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 24px; \n"
"font-weight: bold; ")
        self.lb_5.setObjectName("lb_5")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 981, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 979, 239))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tbTodaySchedule = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tbTodaySchedule.setMinimumSize(QtCore.QSize(100, 100))
        self.tbTodaySchedule.setRowCount(3)
        self.tbTodaySchedule.setObjectName("tbTodaySchedule")
        self.tbTodaySchedule.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tbTodaySchedule.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTodaySchedule.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTodaySchedule.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTodaySchedule.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTodaySchedule.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTodaySchedule.setHorizontalHeaderItem(5, item)
        self.tbTodaySchedule.verticalHeader().setHighlightSections(True)
        self.verticalLayout_7.addWidget(self.tbTodaySchedule)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lb_8 = QtWidgets.QLabel(self.page)
        self.lb_8.setGeometry(QtCore.QRect(11, 344, 337, 45))
        self.lb_8.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 24px; \n"
"font-weight: bold; ")
        self.lb_8.setObjectName("lb_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page)
        self.scrollArea_2.setGeometry(QtCore.QRect(11, 396, 981, 271))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 979, 269))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tbOrtherDay = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tbOrtherDay.setMinimumSize(QtCore.QSize(100, 100))
        self.tbOrtherDay.setRowCount(9)
        self.tbOrtherDay.setObjectName("tbOrtherDay")
        self.tbOrtherDay.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbOrtherDay.setItem(0, 0, item)
        self.tbOrtherDay.verticalHeader().setHighlightSections(True)
        self.verticalLayout_9.addWidget(self.tbOrtherDay)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lb_7 = QtWidgets.QLabel(self.page_3)
        self.lb_7.setMaximumSize(QtCore.QSize(200, 50))
        self.lb_7.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 24px; \n"
"font-weight: bold; ")
        self.lb_7.setObjectName("lb_7")
        self.verticalLayout_10.addWidget(self.lb_7)
        self.widget_5 = QtWidgets.QWidget(self.page_3)
        self.widget_5.setStyleSheet("background-color: white;")
        self.widget_5.setObjectName("widget_5")
        self.widget1 = QtWidgets.QWidget(self.widget_5)
        self.widget1.setGeometry(QtCore.QRect(370, 30, 521, 471))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lb_9 = QtWidgets.QLabel(self.widget1)
        self.lb_9.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 24px; \n"
"font-weight: bold; ")
        self.lb_9.setObjectName("lb_9")
        self.verticalLayout_6.addWidget(self.lb_9)
        self.TxtStudentid = QtWidgets.QLabel(self.widget1)
        self.TxtStudentid.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.TxtStudentid.setObjectName("TxtStudentid")
        self.verticalLayout_6.addWidget(self.TxtStudentid)
        self.TxtClass = QtWidgets.QLabel(self.widget1)
        self.TxtClass.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.TxtClass.setObjectName("TxtClass")
        self.verticalLayout_6.addWidget(self.TxtClass)
        self.txtAcademyYear = QtWidgets.QLabel(self.widget1)
        self.txtAcademyYear.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.txtAcademyYear.setObjectName("txtAcademyYear")
        self.verticalLayout_6.addWidget(self.txtAcademyYear)
        self.TxtMayor = QtWidgets.QLabel(self.widget1)
        self.TxtMayor.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.TxtMayor.setObjectName("TxtMayor")
        self.verticalLayout_6.addWidget(self.TxtMayor)
        self.TxtFaculty = QtWidgets.QLabel(self.widget1)
        self.TxtFaculty.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.TxtFaculty.setObjectName("TxtFaculty")
        self.verticalLayout_6.addWidget(self.TxtFaculty)
        self.widget2 = QtWidgets.QWidget(self.widget_5)
        self.widget2.setGeometry(QtCore.QRect(70, 20, 301, 661))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(0, 0, 10, 200)
        self.verticalLayout_11.setSpacing(7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setStyleSheet("background-color: white;\n"
"color: #2C3E50;\n"
"border: 1.5px solid #2C3E50;\n"
"border-radius: 95%;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"padding: 10px 30px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/logo_vku.jpg"))
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.btnUpdateProfile = QtWidgets.QPushButton(self.widget2)
        self.btnUpdateProfile.setStyleSheet("background-color: #2C3E50;\n"
"color: white;\n"
"border: 1.5px solid #2C3E50;\n"
"border-radius: 5%;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"padding: 10px 30px;")
        self.btnUpdateProfile.setObjectName("btnUpdateProfile")
        self.verticalLayout_11.addWidget(self.btnUpdateProfile)
        self.btnExtractFile = QtWidgets.QPushButton(self.widget2)
        self.btnExtractFile.setStyleSheet("background-color: white;\n"
"color: #2C3E50;\n"
"border: 1.5px solid #2C3E50;\n"
"border-radius: 5%;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"padding: 10px 30px;")
        self.btnExtractFile.setObjectName("btnExtractFile")
        self.verticalLayout_11.addWidget(self.btnExtractFile)
        self.btnUpdateImag = QtWidgets.QPushButton(self.widget2)
        self.btnUpdateImag.setStyleSheet("background-color: #2C3E50;\n"
"color: white;\n"
"border: 1.5px solid #2C3E50;\n"
"border-radius: 5%;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"padding: 10px 30px;")
        self.btnUpdateImag.setObjectName("btnUpdateImag")
        self.verticalLayout_11.addWidget(self.btnUpdateImag)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_4.setGeometry(QtCore.QRect(20, 170, 991, 501))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 989, 499))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tbHistory = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_4)
        self.tbHistory.setMinimumSize(QtCore.QSize(100, 100))
        self.tbHistory.setRowCount(9)
        self.tbHistory.setObjectName("tbHistory")
        self.tbHistory.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tbHistory.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbHistory.setHorizontalHeaderItem(4, item)
        self.tbHistory.verticalHeader().setHighlightSections(True)
        self.verticalLayout_8.addWidget(self.tbHistory)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.lb_6 = QtWidgets.QLabel(self.page_2)
        self.lb_6.setGeometry(QtCore.QRect(0, 20, 281, 45))
        self.lb_6.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 24px; \n"
"font-weight: bold; ")
        self.lb_6.setObjectName("lb_6")
        self.lb_15 = QtWidgets.QLabel(self.page_2)
        self.lb_15.setGeometry(QtCore.QRect(0, 80, 141, 45))
        self.lb_15.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.lb_15.setObjectName("lb_15")
        self.cboxSubject = QtWidgets.QComboBox(self.page_2)
        self.cboxSubject.setGeometry(QtCore.QRect(160, 84, 181, 51))
        self.cboxSubject.setObjectName("cboxSubject")
        self.cboxSubject.addItem("")
        self.cboxSubject.addItem("")
        self.cboxSubject.addItem("")
        self.lb_16 = QtWidgets.QLabel(self.page_2)
        self.lb_16.setGeometry(QtCore.QRect(370, 80, 141, 45))
        self.lb_16.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.lb_16.setObjectName("lb_16")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.page_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(480, 84, 194, 51))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lb_17 = QtWidgets.QLabel(self.page_2)
        self.lb_17.setGeometry(QtCore.QRect(690, 80, 141, 45))
        self.lb_17.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 18px; \n"
"")
        self.lb_17.setObjectName("lb_17")
        self.cboxStatus = QtWidgets.QComboBox(self.page_2)
        self.cboxStatus.setGeometry(QtCore.QRect(810, 80, 181, 51))
        self.cboxStatus.setObjectName("cboxStatus")
        self.cboxStatus.addItem("")
        self.cboxStatus.addItem("")
        self.cboxStatus.addItem("")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1416, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        self.stackedWidget.setCurrentIndex(1)
        self.menubtn.toggled['bool'].connect(self.widget_2.setVisible) # type: ignore
        self.timetablebtn.clicked.connect(self.timetabebtn2.toggle) # type: ignore
        self.timetabebtn2.clicked.connect(self.timetablebtn.toggle) # type: ignore
        self.historybtn.clicked.connect(self.historybtn_2.toggle) # type: ignore
        self.historybtn_2.clicked.connect(self.historybtn.toggle) # type: ignore
        self.userbtn_2.clicked.connect(self.userbtn.toggle) # type: ignore
        self.userbtn.clicked.connect(self.userbtn_2.toggle) # type: ignore
        self.menubtn.toggled['bool'].connect(self.widget.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_4.setText(_translate("MainWindow", "Hello, TraMy"))
        self.timetabebtn2.setText(_translate("MainWindow", "Time table"))
        self.historybtn_2.setText(_translate("MainWindow", "History"))
        self.userbtn_2.setText(_translate("MainWindow", "User"))
        self.logoutbtn_2.setText(_translate("MainWindow", "logout"))
        self.lineEditFind.setPlaceholderText(_translate("MainWindow", "Search"))
        self.lb_5.setText(_translate("MainWindow", "Today\'s schedule"))
        item = self.tbTodaySchedule.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course Title"))
        item = self.tbTodaySchedule.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lecturer"))
        item = self.tbTodaySchedule.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Weeks"))
        item = self.tbTodaySchedule.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Room"))
        item = self.tbTodaySchedule.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Day / Period"))
        item = self.tbTodaySchedule.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Course Schedule"))
        self.lb_8.setText(_translate("MainWindow", "Schedule for other days!"))
        item = self.tbOrtherDay.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbOrtherDay.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course Title"))
        item = self.tbOrtherDay.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lecturer"))
        item = self.tbOrtherDay.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Weeks"))
        item = self.tbOrtherDay.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Room"))
        item = self.tbOrtherDay.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Day / Period"))
        item = self.tbOrtherDay.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Course Schedule"))
        __sortingEnabled = self.tbOrtherDay.isSortingEnabled()
        self.tbOrtherDay.setSortingEnabled(False)
        item = self.tbOrtherDay.item(0, 0)
        item.setText(_translate("MainWindow", "Software Quality Assurance and Testing (2)"))
        self.tbOrtherDay.setSortingEnabled(__sortingEnabled)
        self.lb_7.setText(_translate("MainWindow", "User page"))
        self.lb_9.setText(_translate("MainWindow", f"Hello, student {self.user._name}"))
        self.TxtStudentid.setText(_translate("MainWindow", f"StudentId: {self.user._id}"))
        self.TxtClass.setText(_translate("MainWindow", f"Class: {self.user._homeroom_class}"))
        self.txtAcademyYear.setText(_translate("MainWindow", f"Academy Year: {self.user._school_year}"))
        self.TxtMayor.setText(_translate("MainWindow", f"Major: {self.user._major}"))
        self.TxtFaculty.setText(_translate("MainWindow", f"Faculty: {self.user._faculty}"))

        self.btnUpdateProfile.setText(_translate("MainWindow", "Update profile"))
        self.btnExtractFile.setText(_translate("MainWindow", "Extract file"))
        self.btnUpdateImag.setText(_translate("MainWindow", "Update Image"))
        item = self.tbHistory.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbHistory.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tbHistory.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Subject"))
        item = self.tbHistory.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Session"))
        item = self.tbHistory.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tbHistory.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time "))
        self.lb_6.setText(_translate("MainWindow", " Attendance History"))
        self.lb_15.setText(_translate("MainWindow", "Subject:"))
        self.cboxSubject.setItemText(0, _translate("MainWindow", "New Item"))
        self.cboxSubject.setItemText(1, _translate("MainWindow", "New Item"))
        self.cboxSubject.setItemText(2, _translate("MainWindow", "New Item"))
        self.lb_16.setText(_translate("MainWindow", "Date:"))
        self.lb_17.setText(_translate("MainWindow", "Status:"))
        self.cboxStatus.setItemText(0, _translate("MainWindow", "New Item"))
        self.cboxStatus.setItemText(1, _translate("MainWindow", "New Item"))
        self.cboxStatus.setItemText(2, _translate("MainWindow", "New Item"))


        self.timetabebtn2.clicked.connect(self.handle_timetable)
        self.timetablebtn.clicked.connect(self.handle_timetable)
   
        self.logoutbtn_2.clicked.connect(self.handle_logout)
        self.logoutbtn.clicked.connect(self.handle_logout)
        
        self.historybtn_2.clicked.connect(self.handle_history)
        self.historybtn.clicked.connect(self.handle_history)
        
        self.userbtn_2.clicked.connect(self.handle_user)
        self.userbtn.clicked.connect(self.handle_user)
        
        self.load_schedule()
    def handle_timetable(self):
        print("Nhấn vào nút Thời khóa biểu!")
        self.stackedWidget.setCurrentIndex(0)

    def handle_logout(self):
        print("Đăng xuất!")
    def handle_history(self):
        print("history")
        self.stackedWidget.setCurrentIndex(2)
    def handle_user(self):
        print("Nhấn vào user")
        self.stackedWidget.setCurrentIndex(1)
    def populate_schedule_table(self, schedule):
        self.tbTodaySchedule.setRowCount(len(schedule))
        for row, item in enumerate(schedule):
            self.tbTodaySchedule.setItem(row, 0, QtWidgets.QTableWidgetItem(item.get_day_period()))
            self.tbTodaySchedule.setItem(row, 1, QtWidgets.QTableWidgetItem(item.get_course_title()))
            self.tbTodaySchedule.setItem(row, 2, QtWidgets.QTableWidgetItem(item.get_lecturer()))
            self.tbTodaySchedule.setItem(row, 3, QtWidgets.QTableWidgetItem(item.get_room()))
            self.tbTodaySchedule.setItem(row, 4, QtWidgets.QTableWidgetItem(item.get_weeks()))
            self.tbTodaySchedule.setItem(row, 5, QtWidgets.QTableWidgetItem(item.get_course_schedule()))

    def load_schedule(self):
  
        schedule = self.schedule_controller.get_today_schedule(self.user._id)
        scheduleall = self.schedule_controller.get_all_schedule(self.user._id)
 
        self.populate_schedule_table(schedule)
        self.populate_all_schedule_table(scheduleall)
    def populate_all_schedule_table(self, schedule):
        self.tbOrtherDay.setRowCount(len(schedule))
        for row, item in enumerate(schedule):
            self.tbOrtherDay.setItem(row, 0, QtWidgets.QTableWidgetItem(item.get_day_period()))
            self.tbOrtherDay.setItem(row, 1, QtWidgets.QTableWidgetItem(item.get_course_title()))
            self.tbOrtherDay.setItem(row, 2, QtWidgets.QTableWidgetItem(item.get_lecturer()))
            self.tbOrtherDay.setItem(row, 3, QtWidgets.QTableWidgetItem(item.get_room()))
            self.tbOrtherDay.setItem(row, 4, QtWidgets.QTableWidgetItem(item.get_weeks()))
            self.tbOrtherDay.setItem(row, 5, QtWidgets.QTableWidgetItem(item.get_course_schedule()))

     
import resource_rc


