# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:#F5F7FA;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(270, 0, 551, 111))
        self.label.setStyleSheet("\n"
"color: 2C3E50 ;\n"
"border: none;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(200, 120, 721, 571))
        self.widget.setStyleSheet("border:none;")
        self.widget.setObjectName("widget")
        self.idstudenttxt = QtWidgets.QLineEdit(self.widget)
        self.idstudenttxt.setGeometry(QtCore.QRect(270, 0, 451, 61))
        self.idstudenttxt.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.idstudenttxt.setObjectName("idstudenttxt")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 208, 50))
        self.label_2.setStyleSheet("color: rgb(44, 62, 80);                          \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.label_2.setObjectName("label_2")
        self.lb = QtWidgets.QLabel(self.widget)
        self.lb.setGeometry(QtCore.QRect(0, 70, 190, 50))
        self.lb.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.lb.setObjectName("lb")
        self.btnLogin = QtWidgets.QPushButton(self.widget)
        self.btnLogin.setGeometry(QtCore.QRect(10, 500, 711, 61))
        self.btnLogin.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(self.widget)
        self.btnRegister.setGeometry(QtCore.QRect(10, 430, 711, 61))
        self.btnRegister.setStyleSheet("background-color:#2C3E50;\n"
"    color: white;\n"
"    border: 1.5px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;")
        self.btnRegister.setObjectName("btnRegister")
        self.fullNametxt = QtWidgets.QLineEdit(self.widget)
        self.fullNametxt.setGeometry(QtCore.QRect(270, 70, 451, 61))
        self.fullNametxt.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.fullNametxt.setObjectName("fullNametxt")
        self.lb_2 = QtWidgets.QLabel(self.widget)
        self.lb_2.setGeometry(QtCore.QRect(0, 130, 228, 50))
        self.lb_2.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.lb_2.setObjectName("lb_2")
        self.lb_3 = QtWidgets.QLabel(self.widget)
        self.lb_3.setGeometry(QtCore.QRect(0, 220, 258, 50))
        self.lb_3.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.lb_3.setObjectName("lb_3")
        self.lb_4 = QtWidgets.QLabel(self.widget)
        self.lb_4.setGeometry(QtCore.QRect(0, 350, 249, 50))
        self.lb_4.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.lb_4.setObjectName("lb_4")
        self.dateofbirth = QtWidgets.QDateTimeEdit(self.widget)
        self.dateofbirth.setGeometry(QtCore.QRect(270, 140, 451, 61))
        self.dateofbirth.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.dateofbirth.setObjectName("dateofbirth")
        self.academicYearttxt = QtWidgets.QComboBox(self.widget)
        self.academicYearttxt.setGeometry(QtCore.QRect(270, 210, 451, 61))
        self.academicYearttxt.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.academicYearttxt.setObjectName("academicYearttxt")
        self.academicYearttxt.addItem("")
        self.academicYearttxt.addItem("")
        self.academicYearttxt.addItem("")
        self.lb_5 = QtWidgets.QLabel(self.widget)
        self.lb_5.setGeometry(QtCore.QRect(0, 280, 130, 50))
        self.lb_5.setStyleSheet("color: rgb(44, 62, 80);                \n"
"padding: 8px 16px;   \n"
"font-size: 28px; \n"
"font-weight: bold; ")
        self.lb_5.setObjectName("lb_5")
        self.majortxt = QtWidgets.QComboBox(self.widget)
        self.majortxt.setGeometry(QtCore.QRect(270, 280, 451, 61))
        self.majortxt.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.majortxt.setObjectName("majortxt")
        self.majortxt.addItem("")
        self.advisoryClasstxt = QtWidgets.QComboBox(self.widget)
        self.advisoryClasstxt.setGeometry(QtCore.QRect(270, 350, 451, 61))
        self.advisoryClasstxt.setStyleSheet("background-color: white;\n"
"    color: #2C3E50;\n"
"    border: 1.5px solid #2C3E50;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px 30px;")
        self.advisoryClasstxt.setObjectName("advisoryClasstxt")
        self.advisoryClasstxt.addItem("")
        self.advisoryClasstxt.addItem("")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#2c3e50;\">REGISTER</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Id_student"))
        self.lb.setText(_translate("MainWindow", "Full Name"))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.btnRegister.setText(_translate("MainWindow", "Register"))
        self.lb_2.setText(_translate("MainWindow", "Date of birth"))
        self.lb_3.setText(_translate("MainWindow", "Academic Year"))
        self.lb_4.setText(_translate("MainWindow", "Advisory Class"))
        self.academicYearttxt.setItemText(0, _translate("MainWindow", "2022-2027"))
        self.academicYearttxt.setItemText(1, _translate("MainWindow", "2021-2026"))
        self.academicYearttxt.setItemText(2, _translate("MainWindow", "2022-2026"))
        self.lb_5.setText(_translate("MainWindow", "Major"))
        self.majortxt.setItemText(0, _translate("MainWindow", "Information Teachnology"))
        self.advisoryClasstxt.setItemText(0, _translate("MainWindow", "IT1"))
        self.advisoryClasstxt.setItemText(1, _translate("MainWindow", "SE1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
